info:
  description: "Data Models used for CommunityConduit's IoT Ecosystem"
  title: CommunityConduitModeling
  version: "0.0.2"
openapi: "3.0.3"
paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        "200":
          content:
            application/ld+json:
              schema:
                type: object
          description: OK
components:
  schemas:
    DataModel:
      required:
        - id
        - type
        - name
      properties:
        id:
          <<: *anyof
          description: "Unique identifier of the DataModel entity"
          x-ngsi:
            type: Property
        type:
          description: "NGSI Entity type. It has to be DataModel"
          enum:
            - DataModel
          type: string
          x-ngsi:
            type: Property
        name:
          description: "Name of the data model"
          type: string
          x-ngsi:
            type: Property
        description:
          description: "Description of the data model"
          type: string
          x-ngsi:
            type: Property
        modelFormat:
          description: "Format of the data model"
          type: string
          x-ngsi:
            type: Property
        ontology:
          description: "Ontology of the data model"
          type: string
          x-ngsi:
            type: Property
        ontologyVersion:
          description: "Version of the ontology"
          type: string
          x-ngsi:
            type: Property
        ontologyURL:
          description: "URL to the ontology"
          type: string
          format: uri
          x-ngsi:
            type: Property
        associatedCommunities:
          description: "Communities associated with the data model"
          type: array
          items:
            oneOf:
              - format: uri
                type: string
              - *anyof
          x-ngsi:
            type: Relationship
        dataSharingPolicy:
          description: "Policy for data sharing"
          type: string
          x-ngsi:
            type: Property
      type: object
      x-ngsi:
        uri-prefix: "TBA"

    Community:
      required:
        - id
        - type
        - name
      properties:
        id:
          anyOf: *anyof
          description: "Unique identifier of the community"
          x-ngsi:
            type: Property
        type:
          description: 'NGSI Entity type. It has to be Community'
          enum:
            - Community
          type: string
          x-ngsi:
            type: Property
        name:
          description: "The name of the community"
          type: string
          x-ngsi:
            type: Property
        connectionDetails:
          type: object
          properties:
            protocol:
              description: "Protocol used for the connection"
              type: string
              x-ngsi:
                type: Property
            endpoint:
              description: "Endpoint for the connection"
              type: string
              x-ngsi:
                type: Property
        origin:
          description: "Origin of the community"
          type: string
          x-ngsi:
            type: Property
        roleInFederation:
          description: "Role of community within the federation"
          type: string
          x-ngsi:
            type: Property
        geographicalLocation:
          description: "Geographical location of the community"
          type: string
          x-ngsi:
            type: Property
        hasDataModels:
          description: "Data models that the community possesses"
          type: array
          items:
            oneOf:
              - format: uri
                type: string
              - anyOf: *anyof
                description: "Property. Unique identifier of the data model"
          x-ngsi:
            type: Relationship
        partOfFederation:
          description: "Which federation the community is a part of"
          type: string
          format: uri
          x-ngsi:
            type: Relationship
        lastUpdated:
          description: "Last updated timestamp of the community details"
          type: string
          format: date-time
          x-ngsi:
            type: Property

    Federation:
    required:
      - id
      - type
      - name
    properties:
      id:
        <<: *anyof
        description: "Unique identifier of the Federation entity"
        x-ngsi:
          type: Property
      type:
        description: "NGSI Entity type. It has to be Federation"
        enum:
          - Federation
        type: string
        x-ngsi:
          type: Property
      name:
        description: "Name of the federation"
        type: string
        x-ngsi:
          type: Property
      topology:
        description: "Topology of the federation"
        type: string
        x-ngsi:
          type: Property
      structure:
        description: "Structure of the federation"
        type: string
        x-ngsi:
          type: Property
      areaCovered:
        description: "Area covered by the federation"
        type: string
        x-ngsi:
          type: Property
      numberOfNodes:
        description: "Number of nodes in the federation"
        type: number
        x-ngsi:
          type: Property
      partOfFederation:
        description: "Other federations this federation is part of"
        type: string
        format: uri
        x-ngsi:
          type: Relationship
      includesCommunities:
        description: "Communities included in the federation"
        type: array
        items:
          oneOf:
            - format: uri
              type: string
            - *anyof
        x-ngsi:
          type: Relationship
      usesConnections:
        description: "Connections used by the federation"
        type: array
        items:
          oneOf:
            - format: uri
              type: string
            - *anyof
        x-ngsi:
          type: Relationship
      dataSharingPolicy:
        description: "Data sharing policy of the federation"
        type: string
        x-ngsi:
          type: Property
    type: object
    x-ngsi:
      uri-prefix: "TBA"

CommunityInteraction:
  required:
    - id
    - type
    - initiatedBy
    - from
    - towards
  properties:
    id:
      <<: *anyof
      description: "Unique identifier of the CommunityInteraction entity"
      x-ngsi:
        type: Property
    type:
      description: "NGSI Entity type. It has to be CommunityInteraction"
      enum:
        - CommunityInteraction
      type: string
      x-ngsi:
        type: Property
    initiatedBy:
      description: "Entity that initiated the interaction"
      type: string
      format: uri
      x-ngsi:
        type: Relationship
    from:
      description: "Origin of the interaction"
      type: string
      format: uri
      x-ngsi:
        type: Relationship
    towards:
      description: "Destination of the interaction"
      type: string
      format: uri
      x-ngsi:
        type: Relationship
    dataModelMap:
      description: "Mapping of data models for the interaction"
      type: object
      patternProperties:
        "^urn:ngsild:DataModel_.*$":
          type: string
          format: uri
      additionalProperties: false
      x-ngsi:
        type: Property
    connectionType:
      description: "Type of connection for the interaction"
      type: string
      x-ngsi:
        type: Property
    connectionStatus:
      description: "Status of the connection"
      type: string
      x-ngsi:
        type: Property
  type: object
  x-ngsi:
    uri-prefix: "TBA"